bot_name: "Stalebot"
engine_path: "./Engine/stockfish"
move_time_ms: 100
time_multiplier: 0
blunder_guard_min_think_ms: 180
blunder_guard_verify_ratio: 0.5
blunder_guard_min_verify_ms: 120

uci_options:                          # Arbitrary UCI options passed to the engine.
  Threads: 4                          # Increased threads for Threadripper power.
  Hash: 2508                          # Increased hash for better position evaluation.
  Move Overhead: 100

challenge:
  concurrency: 1
  max_takebacks: 2
  bullet_with_increment_only: false
  # min_increment: 0
  # max_increment: 180
  # min_initial: 0
  # max_initial: 10800
  variants:
    - standard
    - chess960
    - fromPosition
  # - antichess
  # - atomic
  # - crazyhouse
  # - horde
  # - kingOfTheHill
  # - racingKings
  # - threeCheck
  bot_time_controls:
    - bullet
    - blitz
    - rapid
  # - classical
  # - 25+0
  human_time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  bot_modes:
    - casual
   # - rated
  human_modes:
    - casual
    - rated
