name: Update Stockfish to Latest Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-stockfish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download & Unzip Stockfish
        run: |
          curl -L -o stockfish.zip "https://abrok.eu/stockfish/latest/linux/stockfish_x64_avx2.zip"
          unzip -q stockfish.zip

          mkdir -p Engine

          BIN_PATH=$(find . -type f -executable -name "stockfish_*_x64_avx2" | head -n 1)

          if [[ -z "$BIN_PATH" ]]; then
            echo "Stockfish binary not found!"
            exit 1
          fi

          mv "$BIN_PATH" Engine/stockfish
          chmod +x Engine/stockfish

      - name: Commit & Push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Engine/stockfish

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update to latest Stockfish build"
          git push origin HEAD
